# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
