# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160413_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='lat',
            field=models.CharField(blank='true', max_length=100),
        ),
        migrations.AddField(
            model_name='delegation',
            name='lon',
            field=models.CharField(blank='true', max_length=100),
        ),
    ]
