# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160418_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.CharField(blank=True, max_length=100)),
                ('lat', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='lon',
        ),
        migrations.AlterField(
            model_name='prof',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Adresse'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='dele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Delegation'),
        ),
    ]
