# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-27 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_auto_20160421_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
                ('profes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Prof')),
            ],
        ),
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'envoi de message")),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.discussion')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
