# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_devis_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='rendez_vous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('state', models.IntegerField()),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
                ('profess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Prof')),
            ],
        ),
    ]
